# Generated by Django 5.2.4 on 2025-07-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_categories_products_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
